""" Constants related to Entertainment System."""

DOMAIN = "entertainment_system"

CONF_AVAILABILITY = "availability"
CONF_POWER_STATE = "power_state"
CONF_MEDIA_STATE = "media_state"
CONF_REMOTE = "remote"
CONF_SPEAKER = "speaker"

#
#
# CONF_AVAILABILITY_TEMPLATE = "availability_template"
# CONF_MEDIAPLAYER = "media_players"
# ON_ACTION = "turn_on"
# OFF_ACTION = "turn_off"
# PLAY_ACTION = "play"
# STOP_ACTION = "stop"
# PAUSE_ACTION = "pause"
# NEXT_ACTION = "next"
# PREVIOUS_ACTION = "previous"
# VOLUME_UP_ACTION = "volume_up"
# VOLUME_DOWN_ACTION = "volume_down"
# MUTE_ACTION = "mute"
# CURRENT_SOURCE_TEMPLATE = "current_source_template"
# CONF_INPUTS = "inputs"
# TITLE_TEMPLATE = "title_template"
# ARTIST_TEMPLATE = "artist_template"
# ALBUM_TEMPLATE = "album_template"
# CURRENT_VOLUME_TEMPLATE = "current_volume_template"
# CURRENT_IS_MUTED_TEMPLATE = "current_is_muted_template"
# ALBUM_ART_TEMPLATE = "album_art_template"
# SET_VOLUME_ACTION = "set_volume"
# PLAY_MEDIA_ACTION = "play_media"
# MEDIA_CONTENT_TYPE_TEMPLATE = "media_content_type_template"
# MEDIA_IMAGE_URL_TEMPLATE = "media_image_url_template"
# MEDIA_EPISODE_TEMPLATE = "media_episode_template"
# MEDIA_SEASON_TEMPLATE = "media_season_template"
# MEDIA_SERIES_TITLE_TEMPLATE = "media_series_title_template"
# MEDIA_ALBUM_ARTIST_TEMPLATE = "media_album_artist_template"
# SEEK_ACTION = "seek"
# CURRENT_POSITION_TEMPLATE = "current_position_template"
# MEDIA_DURATION_TEMPLATE = "media_duration_template"
# CURRENT_SOUND_MODE_TEMPLATE = "current_sound_mode_template"
# CONF_SOUND_MODES = "sound_modes"
# CONF_UNIQUE_ID = "unique_id"